mode: "patch"

master:
  enhance_feat: True

loader:
  tokenizer:
    lower: 1
    split: " "
    char_level: 0
    oov_token: "<OOV>"
    num_words: 10000
  generator:
    feature_names: "count-syllabels|count-morphemes|count-length"
    list_frequency: "google|wikipedia|subtlex-us|subtlex-uk"
  sentence_maxlen: 256
  token_maxlen: 2

word2vec:
  vector_size: 256
  window: 5
  min_count: 1
  workers: -1
  seed: 42

fasttext:
  vector_size: 256
  window: 3
  min_count: 1
  workers: -1
  seed: 42

regressor:
  trainable_embedding: False
  layer_type: "bigru"
  sentence_unit: 64
  token_unit: 64
  dropout_rate: 0.5
  dense_unit: 32

trainer:
  lr: 0.001
  batch_size: 64
  epochs: 10
  early_stopping_patience: 3
  reduce_lr_factor: 0.2
  reduce_lr_patience: 2
  reduce_lr_min: 0.000001